# Generated by Django 6.0.5 on 2026-05-08 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompatibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название правила')),
                ('spec_key', models.CharField(help_text='Например: socket, form_factor', max_length=100, verbose_name='Ключ характеристики')),
                ('description', models.TextField(verbose_name='Описание правила')),
                ('category_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_as_a', to='configurator.category', verbose_name='Категория A')),
                ('category_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_as_b', to='configurator.category', verbose_name='Категория B')),
            ],
            options={
                'verbose_name': 'Правило совместимости',
                'verbose_name_plural': 'Правила совместимости',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('brand', models.CharField(max_length=100, verbose_name='Производитель')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (USD)')),
                ('specs', models.JSONField(default=dict, verbose_name='Характеристики')),
                ('image', models.ImageField(blank=True, null=True, upload_to='components/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='configurator.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Комплектующее',
                'verbose_name_plural': 'Комплектующие',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сборки')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('components', models.ManyToManyField(blank=True, related_name='builds', to='configurator.component', verbose_name='Комплектующие')),
            ],
            options={
                'verbose_name': 'Сборка',
                'verbose_name_plural': 'Сборки',
                'ordering': ['-created_at'],
            },
        ),
    ]
